route1:
  path:     /addition
  controller: Calculator\Controller\CalculatorController::addition
  methods:    [POST]
  options:
    utf8: true
route2:
  path:     /subtraction
  controller: Calculator\Controller\CalculatorController::subtraction
  methods:    [POST]
  options:
    utf8: true
route3:
  path:     /multiplication
  controller: Calculator\Controller\CalculatorController::multiplication
  methods:    [POST]
  options:
    utf8: true
route4:
  path:     /division
  controller: Calculator\Controller\CalculatorController::division
  methods:    [POST]
  options:
    utf8: true
route5:
  path:     /sqrt
  controller: Calculator\Controller\CalculatorController::sqrt
  methods:    [POST]
  options:
    utf8: true
route6:
  path:     /
  controller: Calculator\Controller\IndexController::index
  methods:    [GET]
  options:
    utf8: true