route1:
  path:     /addition/{numero1}/{numero2}
  defaults: { _controller: 'Calculator\Controller\CalculatorController::addition' }
  options:
    utf8: true
route2:
  path:     /subtraction/{numero1}/{numero2}
  defaults: { _controller: 'Calculator\Controller\CalculatorController::subtraction' }
  options:
    utf8: true
route3:
  path:     /multiplication/{numero1}/{numero2}
  defaults: { _controller: 'Calculator\Controller\CalculatorController::multiplication' }
  options:
    utf8: true
route4:
  path:     /division/{numero1}/{numero2}
  defaults: { _controller: 'Calculator\Controller\CalculatorController::division' }
  options:
    utf8: true
route5:
  path:     /sqrt/{numero1}
  defaults: { _controller: 'Calculator\Controller\CalculatorController::sqrt' }
  options:
    utf8: true
route6:
  path:     /
  defaults: { _controller: 'Calculator\Controller\IndexController::index' }
  options:
    utf8: true